version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | sudo docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            sudo docker build -t $DOCKERHUB_USERNAME/nestjs:$CIRCLE_BUILD_NUM .
      - run:
          name: Push application Docker image
          command: |
            sudo docker push $DOCKERHUB_USERNAME/nestjs:$CIRCLE_BUILD_NUM
            sudo docker tag $DOCKERHUB_USERNAME/nestjs:$CIRCLE_BUILD_NUM $DOCKERHUB_USERNAME/nestjs:latest
            sudo docker push $DOCKERHUB_USERNAME/nestjs:latest
workflows:
  build-deploy:
    jobs:
      - build:
          context: 
            - org-global
            - Docker-Hub
