pool:
  name: Azure Pipelines
steps:
- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: 'Docker-Hub'
    repository: '$(solomonjdavid001)/$(Build.Repository.Name)'
    command: build
    tags: '$(Build.BuildId)'

- task: Docker@2
  displayName: push
  inputs:
    containerRegistry: 'Docker-Hub'
    repository: '$(solomonjdavid001)/$(Build.Repository.Name)'
    command: push
    tags: '$(Build.BuildId)'
